package dev.sinkhole;

import org.cloudburstmc.nbt.NBTInputStream;
import org.cloudburstmc.nbt.NbtMap;
import org.cloudburstmc.nbt.NbtType;
import org.cloudburstmc.nbt.NbtUtils;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Java block state id <-> Bedrock block runtime id.
 *
 * {@code block_palette.nbt} is the Bedrock block palette (index = runtime id, {@code network_id} = hashed id) and
 * {@code block_map.txt} gives, for each Java state id, the palette index of the matching Bedrock state. The map is
 * generated by {@code tools/build_block_map.py} from GeyserMC's published mappings (MIT, see data/NOTICE).
 */
public final class BlockMapper {
    private final int[] javaToBedrock;
    private final int[] bedrockIndexToJava;
    private final Map<Integer, Integer> bedrockHashToJava = new HashMap<>();
    private final int airRuntimeId;

    public BlockMapper() throws IOException {
        List<NbtMap> palette;
        try (NBTInputStream in = NbtUtils.createGZIPReader(resource("/data/block_palette.nbt"))) {
            palette = ((NbtMap) in.readTag()).getList("blocks", NbtType.COMPOUND);
        }
        String[] raw = new String(resource("/data/block_map.txt").readAllBytes(), StandardCharsets.UTF_8).trim().split(",");
        javaToBedrock = new int[raw.length];
        bedrockIndexToJava = new int[palette.size()];
        java.util.Arrays.fill(bedrockIndexToJava, -1);

        int air = -1;
        for (int i = 0; i < palette.size(); i++) {
            if (palette.get(i).getString("name").equals("minecraft:air")) {
                air = i;
                break;
            }
        }
        airRuntimeId = air;

        for (int javaId = 0; javaId < raw.length; javaId++) {
            int idx = Integer.parseInt(raw[javaId]);
            javaToBedrock[javaId] = idx < 0 ? air : idx;
            if (idx >= 0 && bedrockIndexToJava[idx] < 0) {
                bedrockIndexToJava[idx] = javaId;
            }
        }

        // Bedrock states with no Java twin (unused variants) borrow the Java state of another state of the same block.
        Map<String, Integer> byName = new HashMap<>();
        for (int i = 0; i < palette.size(); i++) {
            if (bedrockIndexToJava[i] >= 0) {
                byName.putIfAbsent(palette.get(i).getString("name"), bedrockIndexToJava[i]);
            }
        }
        for (int i = 0; i < palette.size(); i++) {
            if (bedrockIndexToJava[i] < 0) {
                bedrockIndexToJava[i] = byName.getOrDefault(palette.get(i).getString("name"), 0);
            }
            bedrockHashToJava.put(palette.get(i).getInt("network_id"), bedrockIndexToJava[i]);
        }
    }

    public int size() {
        return javaToBedrock.length;
    }

    public int airRuntimeId() {
        return airRuntimeId;
    }

    /** Bedrock runtime id for a Java block state id (air if unknown). */
    public int toBedrock(int javaState) {
        return javaState >= 0 && javaState < javaToBedrock.length ? javaToBedrock[javaState] : airRuntimeId;
    }

    /**
     * Java block state for a Bedrock runtime id. {@code hashed} is StartGame's blockNetworkIdsHashed: the runtime
     * id is then the block-state hash rather than the palette index. Unknown states become air.
     */
    public int toJava(int bedrockRuntimeId, boolean hashed) {
        if (hashed) {
            return bedrockHashToJava.getOrDefault(bedrockRuntimeId, 0);
        }
        return bedrockRuntimeId >= 0 && bedrockRuntimeId < bedrockIndexToJava.length ? bedrockIndexToJava[bedrockRuntimeId] : 0;
    }

    private static InputStream resource(String path) throws IOException {
        InputStream s = BlockMapper.class.getResourceAsStream(path);
        if (s == null) {
            throw new IOException("Missing resource " + path);
        }
        return s;
    }
}
